### ISSUE TITLE
nREPL server doesn't clean up threads created by 'clone'

### ISSUE THREAD

**Issue by zcaudate** [nrepl/nrepl#152]
I found that nrepl creates a thread after every 'clone' operation. However, the thread remains even when the 'close' operation is called. I don't know how to kill it.

## Steps to reproduce the problem

Open an nrepl server in one project (tried with versions 0.6.0 and 0.7.0-alpha1), the port I've set to 51311.

On another project, run this code to connect to the server couple of times to see the thread count increase:

```
(do (def -conn- (nrepl.core/connect :port 51311))
      (def -c1- (nrepl.core/client -conn- 10000))
      (doall (nrepl.core/message -c1- {:op "clone"}))
      (doall (nrepl.core/message -c1- {:op "clone"}))
      (.close -conn-))
```

This next code kills all the sessions, but doesn't kill the threads;

```
(do (def -conn- (nrepl.core/connect :port 51311))
      (def -c1- (nrepl.core/client -conn- 10000))
      (def sessions (first (nrepl.core/message -c1- {:op "ls-sessions"})))
      (doseq [session (:sessions sessions)]
        (nrepl.core/message -c1- {:op "close"
                                  :session session}))
      (.close -conn-))
```

### Clojure version

1.9.0

### Java version

11

### Operating system

MacOS

**Comment by zcaudate** [comment]
the crucial thing is to call the  `(close)` function, defined here:
https://github.com/zcaudate-me/nrepl/blob/15c95cb7dba7643c0ba0e3cc5666bbe8478cf4a4/src/clojure/nrepl/middleware/session.clj#L193

the additional try/catch-loop forms: https://github.com/zcaudate-me/nrepl/commit/f2497f3ccad01c32b32a89afd1aff2f3e21665a9#diff-e28a7dd6eef2522ca6b471c473c41ea0R168-R169 is to suppress the exception:

```
Exception in thread "nRepl-session-4481681a-fd89-4a2f-9a84-0af8607ee38e" java.lang.InterruptedException
#object[nrepl.transport.FnTransport 0x21c12fe1 "nrepl.transport.FnTransport@21c12fe1"]
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2090)
	at java.base/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
	at nrepl.middleware.session$session_exec$main_loop__1038.invoke(session.clj:168)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
