### ISSUE TITLE
Throw Invalid token when read ::auto/resolved keyword.

### ISSUE THREAD

**Issue by defclass** [nrepl/nrepl#182]
## Expected behavior

should read ::auto/resolved keyword in tty transport.

## Actual behavior

Will throw  java.lang.RuntimeException: Invalid token on server side.

## Steps to reproduce the problem

Strart nrepl server with using tty.

```clj
(require '[nrepl.transport :as nrepl-t])

(nrepl/start-server :bind "127.0.0.1" :port 31416 :transport-fn nrepl-t/tty)
```

repl (`nc 127.0.0.1 31416`)

```clj
user=> (ns foo  (:require [clojure.java.io :as io]))
nil
foo=> ::io/abc
```

The server will throw a  "java.lang.RuntimeException: Invalid token" caused by  `clojure.core/read` in https://github.com/nrepl/nrepl/blob/master/src/clojure/nrepl/transport.clj#L159.

By the way, `transport bencode` works fine when using `lein repl`.

also refer: 
https://clojure.atlassian.net/browse/CLJ-2359

## Environment & Version information

0.7.0

### Clojure version

1.10.1

### Java version

1.8

### Operating system

macos 10.13.6

**Comment by bbatsov** [comment]
Thanks for the great issue report. @shen-tian Would you mind taking a look into this one?

**Comment by shen-tian** [comment]
Can reproduce and explain the bug. A simpler error could be just to type `::abc` instead of `::io/abc`. We should expect `:foo/abc`, but get `:user/abc` in my case. Not too sure how to fix though:

https://github.com/nrepl/nrepl/blob/f97a23370ecebc976498b25da46cb69918b88b0b/src/clojure/nrepl/transport.clj#L147-L179

- Line 159 uses `read` to grab the next valid expression. This will auto resolve namespaced keywords. However, this is not ran in the correct namespace, it won't be done correctly. (i.e. `::io/abc` won't find the `io` alias in the `foo` ns).
- Line 165 updates the correct ns. So it fees like if we could just wrap the `read` call in the correct binding for `*ns*` to `@cns`, then this should work...
- Except `read` gets called right after the last expression being received, and before its execution and subsequent ns change.

A few thoughts:

- We can avoid calling `read` here, and just read till end of line or similar, and pass the string through to be read later. But that might be breaking some behaviours for clients that were counting on the "wait till a full expression" behaviour. 
- Can we defer the resolution, but still use `read`? Don't understand the reader mechanics to know if that works. Had a brief look at [LispReader.java](https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/LispReader.java) and don't see anything obvious.
- Should we maintain a string buffer between the socket and `read` so we can have a chance to update the namespace?

The clojure/source issue you linked to could have a similar cause, but definitely doesn't cause this issue.

**Comment by bbatsov** [comment]
Great research!

> It's been around since at least 0.4.0, possibly earlier.

Probably this has always been the case, but back then namespaced keywords didn't exist if I recall correctly. 

I definitely didn't expect this to be so tricky. It'd be nice if we found so way to use the right `ns` instead of jumping hoops around `read`.

**Comment by NickeZ** [comment]
I think I ran into the same issue, got here via google, is this the same issue and are there any workarounds?

backtrace:

```
java.lang.RuntimeException: Invalid token: ::api.redacted/redacted
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.LispReader.interpretToken(LispReader.java:412)
        at clojure.lang.LispReader.read(LispReader.java:305)
        at clojure.lang.LispReader.readDelimitedList(LispReader.java:1398)
        at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1243)
        at clojure.lang.LispReader.read(LispReader.java:285)
        at clojure.lang.LispReader.readDelimitedList(LispReader.java:1398)
        at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1243)
        at clojure.lang.LispReader.read(LispReader.java:285)
        at clojure.lang.LispReader.readDelimitedList(LispReader.java:1398)
        at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1243)
        at clojure.lang.LispReader.read(LispReader.java:285)
        at clojure.lang.LispReader.read(LispReader.java:216)
        at clojure.lang.LispReader.read(LispReader.java:205)
        at clojure.lang.RT.readString(RT.java:1878)
        at clojure.core$read_string.invokeStatic(core.clj:3816)
        at clojure.core$read_string.invoke(core.clj:3805)
        at niddle.print$read_form.invokeStatic(print.clj:79)
        at niddle.print$read_form.invoke(print.clj:79)
        at niddle.print$printable_form.invokeStatic(print.clj:88)
        at niddle.print$printable_form.invoke(print.clj:87)
        at niddle.print$eval3892$fn__3894.invoke(print.clj:92)
        at clojure.lang.MultiFn.invoke(MultiFn.java:229)
        at niddle.print$niddle_mw$fn__3914.invoke(print.clj:126)
        at nrepl.middleware$wrap_conj_descriptor$fn__658.invoke(middleware.clj:16)
        at nrepl.middleware.caught$wrap_caught$fn__926.invoke(caught.clj:97)
        at nrepl.middleware$wrap_conj_descriptor$fn__658.invoke(middleware.clj:16)
        at nrepl.middleware.print$wrap_print$fn__893.invoke(print.clj:234)
        at nrepl.middleware$wrap_conj_descriptor$fn__658.invoke(middleware.clj:16)
        at nrepl.server$default_handler$fn__1586.invoke(server.clj:130)
        at nrepl.server$handle_STAR_.invokeStatic(server.clj:22)
        at nrepl.server$handle_STAR_.invoke(server.clj:19)
        at nrepl.server$handle$fn__1557.invoke(server.clj:39)
        at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```
