### ISSUE TITLE
java.lang.ArithmeticException: long overflow at nrepl.bencode$read_long.invokeStatic(bencode.clj:128)

### ISSUE THREAD

**Issue by theronic** [nrepl/nrepl#285]
Using nrepl version 1.1.0-alpha1, when I run `clj -A:shadow-cljs watch app` against my Clojure v1.11.1 / ClojureScript v1.11.54 app, nREPL.bencode throws an ArithmeticException:

```
ERROR:
java.lang.ArithmeticException: long overflow
        at java.base/java.lang.Math.multiplyExact(Math.java:999)
        at clojure.lang.Numbers.multiply(Numbers.java:1971)
        at nrepl.bencode$read_long.invokeStatic(bencode.clj:128)
        at nrepl.bencode$read_long.invokePrim(bencode.clj)
        at nrepl.bencode$read_netstring_STAR_.invokeStatic(bencode.clj:155)
        at nrepl.bencode$read_netstring_STAR_.invoke(bencode.clj:153)
        at nrepl.bencode$read_token.invokeStatic(bencode.clj:246)
        at nrepl.bencode$read_token.invoke(bencode.clj:236)
        at nrepl.bencode$read_bencode.invokeStatic(bencode.clj:256)
        at nrepl.bencode$read_bencode.invoke(bencode.clj:253)
        at nrepl.transport$bencode$fn__22320$fn__22321.invoke(transport.clj:122)
        at nrepl.transport$bencode$fn__22320.invoke(transport.clj:122)
        at nrepl.transport$fn_transport$fn__22274.invoke(transport.clj:50)
        at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:858)
ERROR:

```

I'm guessing it's some weird incompatibility, possibly related to Carmine. My deps.edn looks like this:

```
{:paths     ["src" "resources"]
 :aliases   {:nrepl       {:extra-deps {nrepl/nrepl      {:mvn/version "1.1.0-alpha1"}
                                        nrepl/drawbridge {:mvn/version "0.2.1"}}}
             :shadow-cljs {:extra-deps {thheller/shadow-cljs {:mvn/version "2.20.6"}}
                           :main-opts  ["-m" "shadow.cljs.devtools.cli"]}}
 :mvn/repos {"central" {:url "https://repo1.maven.org/maven2/"}
             "clojars" {:url "https://clojars.org/repo"}
             "google"  {:url "https://maven.google.com/"}}
 :deps      {org.clojure/clojure                {:mvn/version "1.11.1"}
             org.clojure/clojurescript          {:mvn/version "1.11.54"}

             ;; Async
             org.clojure/core.async             {:mvn/version "1.5.648"}

             ;; Streams / Async
             ;manifold/manifold          {:mvn/version "0.2.4"}

             ;; Logging
             com.taoensso/timbre                {:mvn/version "4.10.0"}

             ;; nREPL (todo alias)
             nrepl/nrepl                        {:mvn/version "1.1.0-alpha1"}

             ;; Lifecycle
             mount/mount                        {:mvn/version "0.1.16"}

             ;; Messaging
             io.nats/jnats                      {:mvn/version "2.15.3"}

             ;; Web Server
             http-kit/http-kit                  {:mvn/version "2.4.0-alpha6"}

             ;; Routing
             metosin/reitit                     {:mvn/version "0.5.18"}

             ;; Web Middleware
             ring/ring                          {:mvn/version "1.9.0"}

             throttler/throttler                {:mvn/version "1.0.1"}

             ;; Rendering
             reagent/reagent                    {:mvn/version "1.1.1"}
             rum/rum                            {:mvn/version "0.12.9"}

             ;; Wire Transport
             com.cognitect/transit-clj          {:mvn/version "1.0.329"}
             com.cognitect/transit-cljs         {:mvn/version "0.8.269"}

             ;; Data
             com.rpl/specter                    {:mvn/version "1.1.3"}

             ;; Dynamic deps at runtime
             clj-commons/pomegranate            {:mvn/version "1.2.1"}

             ;; Database
             com.google.firebase/firebase-admin {:mvn/version "9.0.0"}
             datascript/datascript              {:mvn/version "1.3.13"}
             seancorfield/next.jdbc             {:mvn/version "1.0.424"}
             org.postgresql/postgresql          {:mvn/version "42.4.0"}
             org.xerial/sqlite-jdbc             {:mvn/version "3.36.0.3"}

             ;; Caching (Redis)
             com.taoensso/carmine               {:mvn/version "3.1.0"}

             ;; Codecs
             metosin/jsonista                   {:mvn/version "0.3.5"}}}


```

## Steps to reproduce the problem

Sorry, I will try to do a minimal reproduction soon! Currently blocked on this.

### Clojure version

1.11.1

### Java version

IBM Semeru Runtime Open Edition 18.0.2.0 (build 18.0.2+9)

### Operating system

macOS Monterey 12.4

**Comment by theronic** [comment]
Before the exception, I get this warning:

```
[:app] Build completed. (219 files, 1 compiled, 1 warnings, 7.01s)

------ WARNING #1 - :redef -----------------------------------------------------
 Resource: taoensso/encore.cljc:1026:1
--------------------------------------------------------------------------------
1023 |                                     (if (< n# nmin#) nmin# (if (> n# nmax#) nmax# n#)))))
1024 | 
1025 | (defn pow [n exp] (Math/pow n exp))
1026 | (defn abs [n]     (if (neg? n) (- n) n)) ; #?(:clj (Math/abs n)) reflects
-------^------------------------------------------------------------------------
 abs already refers to: cljs.core/abs being replaced by: taoensso.encore/abs
--------------------------------------------------------------------------------
1027 | (defn round* ; round
1028 |   ([             n] (round* :round nil n))
1029 |   ([type         n] (round* type   nil n))
1030 |   ([type nplaces n]
--------------------------------------------------------------------------------

```

Could it be related?

**Comment by theronic** [comment]
Here is the deps tree. I see thata shadow-cljs pulls in nREPL 1.0.0:

```
$ clj -X:deps tree
org.clojure/clojure 1.11.1
  . org.clojure/spec.alpha 0.3.218
  . org.clojure/core.specs.alpha 0.2.62
throttler/throttler 1.0.1
  X org.clojure/core.async 0.4.490 :use-top
com.google.firebase/firebase-admin 9.0.0
  . com.google.api-client/google-api-client 1.35.1
    . com.google.oauth-client/google-oauth-client 1.34.1
      . com.google.http-client/google-http-client 1.42.0
      . com.google.http-client/google-http-client-gson 1.42.0
      X com.google.guava/guava 31.1-android :older-version
    . com.google.http-client/google-http-client-gson 1.42.0
      . com.google.http-client/google-http-client 1.42.0
      . com.google.code.gson/gson 2.9.0
    . com.google.guava/guava 31.1-jre
    . com.google.http-client/google-http-client-apache-v2 1.42.0
      . com.google.http-client/google-http-client 1.42.0
      . org.apache.httpcomponents/httpclient 4.5.13
      . org.apache.httpcomponents/httpcore 4.4.15
    . org.apache.httpcomponents/httpcore 4.4.15 :newer-version
    . org.apache.httpcomponents/httpclient 4.5.13 :newer-version
      X org.apache.httpcomponents/httpcore 4.4.13 :older-version
      . commons-logging/commons-logging 1.2
      X commons-codec/commons-codec 1.11 :older-version
    . com.google.http-client/google-http-client 1.42.0 :newer-version
      . org.apache.httpcomponents/httpclient 4.5.13
      . org.apache.httpcomponents/httpcore 4.4.15
      . com.google.code.findbugs/jsr305 3.0.2
      X com.google.guava/guava 30.1.1-android :older-version
      . com.google.j2objc/j2objc-annotations 1.3
      . io.opencensus/opencensus-api 0.31.1
        X io.grpc/grpc-context 1.27.2 :older-version
      . io.opencensus/opencensus-contrib-http-util 0.31.1
        . io.opencensus/opencensus-api 0.31.1
        X com.google.guava/guava 29.0-android :older-version
  . com.google.api-client/google-api-client-gson 1.35.1
    . com.google.api-client/google-api-client 1.35.1
    . com.google.http-client/google-http-client 1.42.0
    . com.google.http-client/google-http-client-gson 1.42.0
  X com.google.http-client/google-http-client 1.41.8 :superseded
    X org.apache.httpcomponents/httpclient 4.5.13 :parent-omitted
    X org.apache.httpcomponents/httpcore 4.4.15 :parent-omitted
    X com.google.code.findbugs/jsr305 3.0.2 :parent-omitted
    X com.google.guava/guava 30.1.1-android :parent-omitted
    X com.google.j2objc/j2objc-annotations 1.3 :parent-omitted
    X io.opencensus/opencensus-api 0.31.0 :parent-omitted
    X io.opencensus/opencensus-contrib-http-util 0.31.0 :parent-omitted
  . com.google.api/api-common 2.2.0
    . com.google.guava/guava 31.1-jre
    . com.google.code.findbugs/jsr305 3.0.2
    . javax.annotation/javax.annotation-api 1.3.2
    . com.google.auto.value/auto-value-annotations 1.9
  . com.google.auth/google-auth-library-oauth2-http 1.7.0
    . com.google.auto.value/auto-value-annotations 1.9
    . com.google.code.findbugs/jsr305 3.0.2
    . com.google.auth/google-auth-library-credentials 1.7.0
    X com.google.http-client/google-http-client 1.41.8 :older-version
    X com.google.http-client/google-http-client-gson 1.41.8 :older-version
    X com.google.guava/guava 31.0.1-android :older-version
  . com.google.cloud/google-cloud-storage 2.7.2
    . com.google.guava/guava 31.1-jre
    . com.google.guava/failureaccess 1.0.1
    . com.google.guava/listenablefuture 9999.0-empty-to-avoid-conflict-with-guava
    . org.checkerframework/checker-qual 3.22.0 :newer-version
    . com.google.j2objc/j2objc-annotations 1.3
    X com.google.http-client/google-http-client 1.41.8 :older-version
    . io.opencensus/opencensus-contrib-http-util 0.31.1
    . com.google.http-client/google-http-client-jackson2 1.41.8
    X com.google.api-client/google-api-client 1.34.1 :older-version
    X com.google.oauth-client/google-oauth-client 1.33.3 :older-version
    X com.google.http-client/google-http-client-gson 1.41.8 :older-version
    X com.google.http-client/google-http-client-apache-v2 1.41.8 :older-version
    . com.google.apis/google-api-services-storage v1-rev20220509-1.32.1
    . com.google.code.gson/gson 2.9.0
    . com.google.cloud/google-cloud-core 2.7.1
    . com.google.auto.value/auto-value-annotations 1.9
    . com.google.api.grpc/proto-google-common-protos 2.8.3
    . com.google.cloud/google-cloud-core-http 2.7.1
    . com.google.http-client/google-http-client-appengine 1.41.8
    . com.google.api/gax-httpjson 0.103.1
    . com.google.api/gax 2.18.1
    . com.google.auth/google-auth-library-credentials 1.7.0
    . com.google.auth/google-auth-library-oauth2-http 1.7.0
    . com.google.api/api-common 2.2.0
    . javax.annotation/javax.annotation-api 1.3.2
    . io.opencensus/opencensus-api 0.31.1
    . io.grpc/grpc-context 1.46.0
    . com.google.api.grpc/proto-google-iam-v1 1.3.4
    . com.google.protobuf/protobuf-java 3.20.1
    . com.google.protobuf/protobuf-java-util 3.20.1
    . org.threeten/threetenbp 1.6.0
    . com.fasterxml.jackson.core/jackson-core 2.13.3 :newer-version
    . com.google.code.findbugs/jsr305 3.0.2
  . com.google.cloud/google-cloud-firestore 3.2.0
    . com.google.cloud/google-cloud-core-grpc 2.7.1
    . io.grpc/grpc-core 1.46.0
    . com.google.android/annotations 4.1.1.4
    . org.codehaus.mojo/animal-sniffer-annotations 1.21
    . io.perfmark/perfmark-api 0.25.0
    X com.google.http-client/google-http-client 1.41.8 :older-version
    . org.apache.httpcomponents/httpclient 4.5.13
    . commons-logging/commons-logging 1.2
    . commons-codec/commons-codec 1.15
    . org.apache.httpcomponents/httpcore 4.4.15
    . io.opencensus/opencensus-contrib-http-util 0.31.1
    . com.google.api.grpc/proto-google-cloud-firestore-v1 3.2.0
      . javax.annotation/javax.annotation-api 1.3.2
      . com.google.auto.value/auto-value-annotations 1.9
      . com.google.guava/failureaccess 1.0.1
      . com.google.guava/listenablefuture 9999.0-empty-to-avoid-conflict-with-guava
      . com.google.code.findbugs/jsr305 3.0.2
      . org.checkerframework/checker-qual 3.22.0
      . com.google.errorprone/error_prone_annotations 2.13.1
      . com.google.j2objc/j2objc-annotations 1.3
    . com.google.cloud/proto-google-cloud-firestore-bundle-v1 3.2.0
      . com.google.api/api-common 2.2.0
      . javax.annotation/javax.annotation-api 1.3.2
      . com.google.auto.value/auto-value-annotations 1.9
      . com.google.api.grpc/proto-google-common-protos 2.8.3
      . com.google.guava/guava 31.1-jre
      . com.google.guava/failureaccess 1.0.1
      . com.google.guava/listenablefuture 9999.0-empty-to-avoid-conflict-with-guava
      . com.google.code.findbugs/jsr305 3.0.2
      . org.checkerframework/checker-qual 3.22.0
      . com.google.errorprone/error_prone_annotations 2.13.1
      . com.google.j2objc/j2objc-annotations 1.3
    . com.google.auto.value/auto-value-annotations 1.9
    . io.opencensus/opencensus-contrib-grpc-util 0.31.1
    . com.google.code.findbugs/jsr305 3.0.2
    . com.google.api/api-common 2.2.0
    . javax.annotation/javax.annotation-api 1.3.2
    . io.grpc/grpc-protobuf 1.46.0
    . io.grpc/grpc-protobuf-lite 1.46.0
    . io.grpc/grpc-context 1.46.0
    . com.google.protobuf/protobuf-java 3.20.1
    . com.google.api.grpc/proto-google-common-protos 2.8.3
    . com.google.api/gax 2.18.1
    . io.grpc/grpc-api 1.46.0
    . com.google.errorprone/error_prone_annotations 2.13.1
    . com.google.api/gax-grpc 2.18.1
    . io.grpc/grpc-alts 1.46.0
    . io.grpc/grpc-grpclb 1.46.0
    . org.conscrypt/conscrypt-openjdk-uber 2.5.1
    . io.grpc/grpc-auth 1.46.0
    . io.grpc/grpc-netty-shaded 1.46.0
    . io.grpc/grpc-googleapis 1.46.0
    . io.grpc/grpc-xds 1.46.0
    . io.grpc/grpc-services 1.46.0
    . com.google.re2j/re2j 1.5
    . org.bouncycastle/bcpkix-jdk15on 1.67
    . org.bouncycastle/bcprov-jdk15on 1.67
    . io.opencensus/opencensus-proto 0.2.0
    . com.google.guava/guava 31.1-jre
    . com.google.guava/failureaccess 1.0.1
    . com.google.guava/listenablefuture 9999.0-empty-to-avoid-conflict-with-guava
    . org.checkerframework/checker-qual 3.22.0
    . com.google.j2objc/j2objc-annotations 1.3
    . org.threeten/threetenbp 1.6.0
    . io.grpc/grpc-stub 1.46.0
    . io.opencensus/opencensus-api 0.31.1
    . com.google.auth/google-auth-library-credentials 1.7.0
    . com.google.cloud/google-cloud-core 2.7.1
    . com.google.api.grpc/proto-google-iam-v1 1.3.4
    . com.google.auth/google-auth-library-oauth2-http 1.7.0
    X com.google.http-client/google-http-client-gson 1.41.8 :older-version
    . com.google.code.gson/gson 2.9.0
    . com.google.protobuf/protobuf-java-util 3.20.1
  . com.google.guava/guava 31.1-jre
    . com.google.guava/failureaccess 1.0.1
    . com.google.guava/listenablefuture 9999.0-empty-to-avoid-conflict-with-guava
    . com.google.code.findbugs/jsr305 3.0.2
    X org.checkerframework/checker-qual 3.12.0 :older-version
    X com.google.errorprone/error_prone_annotations 2.11.0 :older-version
    . com.google.j2objc/j2objc-annotations 1.3
  . org.slf4j/slf4j-api 1.7.36
  . io.netty/netty-codec-http 4.1.77.Final
    . io.netty/netty-common 4.1.77.Final
    . io.netty/netty-buffer 4.1.77.Final
      . io.netty/netty-common 4.1.77.Final
    . io.netty/netty-transport 4.1.77.Final
    . io.netty/netty-codec 4.1.77.Final
      . io.netty/netty-common 4.1.77.Final
      . io.netty/netty-buffer 4.1.77.Final
      . io.netty/netty-transport 4.1.77.Final
    . io.netty/netty-handler 4.1.77.Final
  . io.netty/netty-handler 4.1.77.Final
    . io.netty/netty-common 4.1.77.Final
    . io.netty/netty-resolver 4.1.77.Final
      . io.netty/netty-common 4.1.77.Final
    . io.netty/netty-buffer 4.1.77.Final
    . io.netty/netty-transport 4.1.77.Final
    . io.netty/netty-codec 4.1.77.Final
  . io.netty/netty-transport 4.1.77.Final
    . io.netty/netty-common 4.1.77.Final
    . io.netty/netty-buffer 4.1.77.Final
    . io.netty/netty-resolver 4.1.77.Final
com.cognitect/transit-cljs 0.8.269
  . com.cognitect/transit-js 0.8.874
thheller/shadow-cljs 2.20.6
  . org.clojure/data.json 2.4.0
  . org.clojure/tools.cli 1.0.206
  . org.clojure/tools.reader 1.3.6
  . nrepl/nrepl 1.0.0
  . cider/piggieback 0.5.3
  X com.cognitect/transit-clj 1.0.329 :use-top
  X com.cognitect/transit-cljs 0.8.280 :use-top
  X org.clojure/core.async 1.5.648 :use-top
  X com.google.guava/guava 31.0.1-jre :older-version
  X org.clojure/clojurescript 1.11.60 :use-top
  . com.google.javascript/closure-compiler-unshaded v20220803
  . org.clojure/google-closure-library 0.0-20211011-0726fdeb
    . org.clojure/google-closure-library-third-party 0.0-20211011-0726fdeb
  . org.clojure/google-closure-library-third-party 0.0-20211011-0726fdeb
  . thheller/shadow-util 0.7.0
    . hiccup/hiccup 1.0.5
  . thheller/shadow-client 1.3.3
    X org.clojure/core.async 0.3.443 :use-top
    . hiccup/hiccup 1.0.5
  . thheller/shadow-undertow 0.3.0
    X org.clojure/core.async 1.5.648 :use-top
    . io.undertow/undertow-core 2.2.4.Final
      . org.jboss.logging/jboss-logging 3.4.1.Final
      . org.jboss.xnio/xnio-api 3.8.0.Final
        . org.wildfly.common/wildfly-common 1.5.2.Final
        . org.wildfly.client/wildfly-client-config 1.0.1.Final
          X org.jboss.logging/jboss-logging 3.3.1.Final :older-version
          X org.wildfly.common/wildfly-common 1.2.0.Final :older-version
      . org.jboss.xnio/xnio-nio 3.8.0.Final
        . org.jboss.xnio/xnio-api 3.8.0.Final
          X org.jboss.threads/jboss-threads 2.3.3.Final :older-version
      . org.jboss.threads/jboss-threads 3.1.0.Final
        . org.jboss.logging/jboss-logging 3.4.1.Final
  . thheller/shadow-cljsjs 0.0.22
  . hiccup/hiccup 1.0.5
  . ring/ring-core 1.9.5
    . ring/ring-codec 1.1.3
      . commons-codec/commons-codec 1.15
    . commons-io/commons-io 2.10.0
    . commons-fileupload/commons-fileupload 1.4
      X commons-io/commons-io 2.2 :older-version
    . crypto-random/crypto-random 1.2.1
      . commons-codec/commons-codec 1.15
    . crypto-equality/crypto-equality 1.0.0
  . io.methvin/directory-watcher 0.16.1
    . net.java.dev.jna/jna 5.12.1
    . org.slf4j/slf4j-api 1.7.36
  . expound/expound 0.9.0
  . fipp/fipp 0.6.26
    . org.clojure/core.rrb-vector 0.1.2
  . com.bhauman/cljs-test-display 0.1.1
org.clojure/clojurescript 1.11.54
  X com.google.javascript/closure-compiler-unshaded v20220502 :older-version
  . org.clojure/google-closure-library 0.0-20211011-0726fdeb
  . org.clojure/tools.reader 1.3.6
  . com.cognitect/transit-java 1.0.362
    X com.fasterxml.jackson.core/jackson-core 2.8.7 :older-version
    . org.msgpack/msgpack 0.6.12
      . com.googlecode.json-simple/json-simple 1.1.1
      . org.javassist/javassist 3.18.1-GA
    . javax.xml.bind/jaxb-api 2.3.0
com.taoensso/carmine 3.1.0
  . com.taoensso/encore 3.9.2
    X org.clojure/tools.reader 1.3.3 :older-version
    . com.taoensso/truss 1.6.0
  X com.taoensso/timbre 5.1.0 :use-top
  . com.taoensso/nippy 3.1.1
    X org.clojure/tools.reader 1.3.4 :older-version
    . com.taoensso/encore 3.9.2
    . org.iq80.snappy/snappy 0.4
    . org.tukaani/xz 1.8
    . org.lz4/lz4-java 1.7.1
  . org.apache.commons/commons-pool2 2.9.0
  . commons-codec/commons-codec 1.15
org.postgresql/postgresql 42.4.0
  X org.checkerframework/checker-qual 3.5.0 :superseded
io.nats/jnats 2.15.3
  . net.i2p.crypto/eddsa 0.3.0
rum/rum 0.12.9
  . cljsjs/react 16.8.6-0
  . cljsjs/react-dom 16.8.6-0
    . cljsjs/react 16.8.6-0
seancorfield/next.jdbc 1.0.424
  . org.clojure/java.data 1.0.64
    . org.clojure/tools.logging 0.6.0
reagent/reagent 1.1.1
com.taoensso/timbre 4.10.0
  X com.taoensso/encore 2.91.0 :older-version
  . io.aviso/pretty 0.1.33
com.cognitect/transit-clj 1.0.329
  . com.cognitect/transit-java 1.0.362
datascript/datascript 1.3.13
  . persistent-sorted-set/persistent-sorted-set 0.1.4
mount/mount 0.1.16
com.rpl/specter 1.1.3
  . riddley/riddley 0.1.12
org.xerial/sqlite-jdbc 3.36.0.3
clj-commons/pomegranate 1.2.1
  . org.apache.maven/maven-resolver-provider 3.6.1
    . org.apache.maven/maven-model 3.6.1
      . org.codehaus.plexus/plexus-utils 3.2.0
    . org.apache.maven/maven-model-builder 3.6.1
      . org.codehaus.plexus/plexus-utils 3.2.0
      . org.codehaus.plexus/plexus-interpolation 1.25
      . org.codehaus.plexus/plexus-component-annotations 1.7.1
      . org.apache.maven/maven-model 3.6.1
      . org.apache.maven/maven-artifact 3.6.1
        . org.codehaus.plexus/plexus-utils 3.2.0
        . org.apache.commons/commons-lang3 3.8.1
      . org.apache.maven/maven-builder-support 3.6.1
    . org.apache.maven/maven-repository-metadata 3.6.1
      . org.codehaus.plexus/plexus-utils 3.2.0
    . org.apache.maven.resolver/maven-resolver-api 1.3.3
    . org.apache.maven.resolver/maven-resolver-spi 1.3.3
    . org.apache.maven.resolver/maven-resolver-util 1.3.3
    . org.apache.maven.resolver/maven-resolver-impl 1.3.3
    . org.codehaus.plexus/plexus-utils 3.2.0
    . javax.inject/javax.inject 1
    X org.slf4j/slf4j-api 1.7.25 :older-version
  . org.apache.maven.resolver/maven-resolver-api 1.3.3
  . org.apache.maven.resolver/maven-resolver-spi 1.3.3
    . org.apache.maven.resolver/maven-resolver-api 1.3.3
  . org.apache.maven.resolver/maven-resolver-util 1.3.3
    . org.apache.maven.resolver/maven-resolver-api 1.3.3
  . org.apache.maven.resolver/maven-resolver-impl 1.3.3
    . org.apache.maven.resolver/maven-resolver-api 1.3.3
    . org.apache.maven.resolver/maven-resolver-spi 1.3.3
    . org.apache.maven.resolver/maven-resolver-util 1.3.3
    X org.slf4j/slf4j-api 1.7.25 :older-version
  . org.apache.maven.resolver/maven-resolver-transport-file 1.3.3
    . org.apache.maven.resolver/maven-resolver-api 1.3.3
    . org.apache.maven.resolver/maven-resolver-spi 1.3.3
    X org.slf4j/slf4j-api 1.7.25 :older-version
  . org.apache.maven.resolver/maven-resolver-transport-http 1.3.3
    . org.apache.maven.resolver/maven-resolver-api 1.3.3
    . org.apache.maven.resolver/maven-resolver-spi 1.3.3
    . org.apache.maven.resolver/maven-resolver-util 1.3.3
    X org.apache.httpcomponents/httpclient 4.5.6 :older-version
    X org.apache.httpcomponents/httpcore 4.4.10 :older-version
    . org.slf4j/jcl-over-slf4j 1.7.25
      X org.slf4j/slf4j-api 1.7.25 :older-version
    X org.slf4j/slf4j-api 1.7.25 :older-version
  . org.apache.maven.resolver/maven-resolver-transport-wagon 1.3.3
    . org.apache.maven.resolver/maven-resolver-api 1.3.3
    . org.apache.maven.resolver/maven-resolver-spi 1.3.3
    . org.apache.maven.resolver/maven-resolver-util 1.3.3
    X org.apache.maven.wagon/wagon-provider-api 3.0.0 :older-version
    X org.slf4j/slf4j-api 1.7.25 :older-version
  . org.apache.maven.resolver/maven-resolver-connector-basic 1.3.3
    . org.apache.maven.resolver/maven-resolver-api 1.3.3
    . org.apache.maven.resolver/maven-resolver-spi 1.3.3
    . org.apache.maven.resolver/maven-resolver-util 1.3.3
    X org.slf4j/slf4j-api 1.7.25 :older-version
  . org.tcrawley/dynapath 1.0.0
  . org.apache.maven.wagon/wagon-provider-api 3.3.4
    . org.codehaus.plexus/plexus-utils 3.2.0
  . org.apache.maven.wagon/wagon-http 3.3.4
    . org.apache.maven.wagon/wagon-http-shared 3.3.4
      . org.jsoup/jsoup 1.12.1
      X org.apache.httpcomponents/httpclient 4.5.9 :older-version
      X org.apache.httpcomponents/httpcore 4.4.11 :older-version
      X commons-io/commons-io 2.6 :older-version
      X org.slf4j/slf4j-api 1.7.25 :older-version
      . org.apache.maven.wagon/wagon-provider-api 3.3.4
    X org.apache.httpcomponents/httpclient 4.5.9 :older-version
    X org.apache.httpcomponents/httpcore 4.4.11 :older-version
    . org.slf4j/jcl-over-slf4j 1.7.25
    . org.codehaus.plexus/plexus-utils 3.2.0
    . org.apache.maven.wagon/wagon-provider-api 3.3.4
  X org.apache.httpcomponents/httpclient 4.5.8 :superseded
    X org.apache.httpcomponents/httpcore 4.4.11 :parent-omitted
    X commons-logging/commons-logging 1.2 :parent-omitted
    X commons-codec/commons-codec 1.11 :parent-omitted
  X org.apache.httpcomponents/httpcore 4.4.11 :superseded
metosin/jsonista 0.3.5
  X com.fasterxml.jackson.core/jackson-core 2.13.0 :superseded
  X com.fasterxml.jackson.core/jackson-databind 2.13.0 :superseded
    X com.fasterxml.jackson.core/jackson-annotations 2.13.0 :parent-omitted
    X com.fasterxml.jackson.core/jackson-core 2.13.0 :parent-omitted
  . com.fasterxml.jackson.datatype/jackson-datatype-jsr310 2.13.0
    X com.fasterxml.jackson.core/jackson-annotations 2.13.0 :superseded
    X com.fasterxml.jackson.core/jackson-core 2.13.0 :older-version
    X com.fasterxml.jackson.core/jackson-databind 2.13.0 :older-version
metosin/reitit 0.5.18
  . metosin/reitit-core 0.5.18
    . meta-merge/meta-merge 1.0.0
  . metosin/reitit-dev 0.5.18
    . metosin/reitit-core 0.5.18
    . com.bhauman/spell-spec 0.1.2
    . expound/expound 0.9.0
    X fipp/fipp 0.6.25 :older-version
  . metosin/reitit-spec 0.5.18
    . metosin/reitit-core 0.5.18
    . metosin/spec-tools 0.10.5
      X org.clojure/spec.alpha 0.2.187 :older-version
  . metosin/reitit-malli 0.5.18
    . metosin/reitit-core 0.5.18
    . metosin/malli 0.8.2
      . borkdude/dynaload 0.2.2
      . borkdude/edamame 0.0.19
        X org.clojure/tools.reader 1.3.4 :older-version
      . org.clojure/test.check 1.1.1
      X fipp/fipp 0.6.25 :older-version
      . mvxcvi/arrangement 2.0.0
  . metosin/reitit-schema 0.5.18
    . metosin/reitit-core 0.5.18
    . metosin/schema-tools 0.12.3
      . prismatic/schema 1.1.12
  . metosin/reitit-ring 0.5.18
    . metosin/reitit-core 0.5.18
    . ring/ring-core 1.9.5
  . metosin/reitit-middleware 0.5.18
    . metosin/reitit-ring 0.5.18
    . lambdaisland/deep-diff 0.0-47
      . mvxcvi/puget 1.1.2
        X mvxcvi/arrangement 1.2.0 :older-version
        X fipp/fipp 0.6.17 :older-version
      X fipp/fipp 0.6.17 :older-version
      X org.clojure/core.rrb-vector 0.0.14 :older-version
      . tech.droit/clj-diff 1.0.1
      X mvxcvi/arrangement 1.2.0 :older-version
    . metosin/muuntaja 0.6.8
      X metosin/jsonista 0.3.1 :use-top
      X com.cognitect/transit-clj 1.0.324 :use-top
    . metosin/spec-tools 0.10.5
  . metosin/reitit-http 0.5.18
    . metosin/reitit-core 0.5.18
    . metosin/reitit-ring 0.5.18
  . metosin/reitit-interceptors 0.5.18
    . metosin/reitit-ring 0.5.18
    . lambdaisland/deep-diff 0.0-47
    . metosin/muuntaja 0.6.8
  . metosin/reitit-swagger 0.5.18
    . metosin/reitit-core 0.5.18
  . metosin/reitit-swagger-ui 0.5.18
    . metosin/reitit-ring 0.5.18
    X metosin/jsonista 0.3.5 :use-top
    . metosin/ring-swagger-ui 4.3.0
  . metosin/reitit-frontend 0.5.18
    . metosin/reitit-core 0.5.18
  . metosin/reitit-sieppari 0.5.18
    . metosin/reitit-core 0.5.18
    . metosin/sieppari 0.0.0-alpha13
  X com.fasterxml.jackson.core/jackson-core 2.13.2 :superseded
  . com.fasterxml.jackson.core/jackson-databind 2.13.2.2 :newer-version
    . com.fasterxml.jackson.core/jackson-annotations 2.13.2 :newer-version
    X com.fasterxml.jackson.core/jackson-core 2.13.2 :older-version
ring/ring 1.9.0
  X ring/ring-core 1.9.0 :older-version
  . ring/ring-devel 1.9.0
    X ring/ring-core 1.9.0 :older-version
    . hiccup/hiccup 1.0.5
    . clj-stacktrace/clj-stacktrace 0.2.8
    . ns-tracker/ns-tracker 0.4.0
      . org.clojure/tools.namespace 0.2.11
      . org.clojure/java.classpath 0.3.0
  . ring/ring-jetty-adapter 1.9.0
    X ring/ring-core 1.9.0 :older-version
    . ring/ring-servlet 1.9.0
    . org.eclipse.jetty/jetty-server 9.4.31.v20200723
      . javax.servlet/javax.servlet-api 3.1.0
      . org.eclipse.jetty/jetty-http 9.4.31.v20200723
        . org.eclipse.jetty/jetty-util 9.4.31.v20200723
        . org.eclipse.jetty/jetty-io 9.4.31.v20200723
      . org.eclipse.jetty/jetty-io 9.4.31.v20200723
        . org.eclipse.jetty/jetty-util 9.4.31.v20200723
  . ring/ring-servlet 1.9.0
    X ring/ring-core 1.9.0 :older-version
org.clojure/core.async 1.5.648
  . org.clojure/tools.analyzer.jvm 1.2.2
    . org.clojure/tools.analyzer 1.1.0
    . org.clojure/core.memoize 1.0.253
      . org.clojure/core.cache 1.0.225
        . org.clojure/data.priority-map 1.1.0
    . org.ow2.asm/asm 9.2
    . org.clojure/tools.reader 1.3.6
http-kit/http-kit 2.4.0-alpha6
```

**Comment by ieugen** [comment]
We are also getting this exception and we are not using shadow-cljs . 
Just started investigating it's cause.

**Comment by theronic** [comment]
Just got hit by this again on another project using nrepl v1.1.0-alpha1. Any updates?

**Comment by theronic** [comment]
This seems to happen if Connection type is of type "Socket Repl" instead of "nREPL".

![image](https://github.com/nrepl/nrepl/assets/1011676/eb199a98-4361-422d-b64e-909ef1424b6e)

**Comment by bbatsov** [comment]
I haven't looked into this yet, as I don't do much work with ClojureScript.

**Comment by bbatsov** [comment]
Just to be clear - this problem doesn't exist with nREPL 1.0, right?

**Comment by alexander-yakushev** [comment]
Looks like this happens when somebody starts sending non-bencode input to nREPL. The sequence of bytes is interpreted as a number by Bencode reader up until the number grows so large that the number cannot be accumulated in a single `long` anymore.

I don't see what can be done about this. Maybe, for easier troubleshooting, we can throw a more helpful exception if the very first value in the bencode stream is unparsable like this one.

**Comment by bbatsov** [comment]
> I don't see what can be done about this. Maybe, for easier troubleshooting, we can throw a more helpful exception if the very first value in the bencode stream is unparsable like this one.

That'd be a step in the right direction for sure.

**Comment by Sleepful** [comment]
what is the solution for this? 😓

**Comment by alexander-yakushev** [comment]
This has been fixed in newer nrepl versions. Chances are that you encounter this with an older nrepl version (e.g. 1.0.0).
