### ISSUE TITLE
ClassCastException on re-connect to unix socket

### ISSUE THREAD

**Issue by rrudakov** [nrepl/nrepl#299]
## Steps to reproduce the problem

1. Create a minimal `deps.edn` project:
```clojure
{:paths   ["src"]
 :deps    {}
 :aliases {:socket-nrepl
           {:extra-deps {com.kohlschutter.junixsocket/junixsocket-common        {:mvn/version "2.7.0"}
                         com.kohlschutter.junixsocket/junixsocket-native-common {:mvn/version "2.7.0"}
                         nrepl/nrepl                                            {:mvn/version "1.0.0"}
                         cider/cider-nrepl                                      {:mvn/version "0.30.0"}
                         refactor-nrepl/refactor-nrepl                          {:mvn/version "3.9.0"}}
            :main-opts  ["-m" "nrepl.cmdline"
                         "--middleware" "[refactor-nrepl.middleware/wrap-refactor,cider.nrepl/cider-middleware]"
                         "--socket" "nrepl.sock"]}}}

```
2. Start nrepl:
```bash
clj -M:socket-nrepl
```
3. Connect to nrepl (I use `cider-connect-clj`) - no errors
4. Disconnect from nrepl then connect again.

## Expected behavior

Successful connection to nrepl without errors.

## Actual behavior

Connection established, but with the following exception:
```
ERROR: Unhandled REPL handler exception processing message {:op init-debugger, :nrepl.middleware.print/stream? 1, :nrepl.middleware.print/print cider.nrepl.pprint/pprint, :nrepl.middleware.print/quota 1048576, :nrepl.middleware.print/buffer-size 4096, :nrepl.middleware.print/options {:right-margin 70}, :session c9fe0d83-69cc-4c42-88af-29e5c241be7f, :id 6}
java.lang.ClassCastException: class sun.nio.ch.SocketChannelImpl cannot be cast to class java.net.Socket (sun.nio.ch.SocketChannelImpl and java.net.Socket are in module java.base of loader 'bootstrap')
	at nrepl.transport$bencode$fn__735.invoke(transport.clj:128)
	at nrepl.transport.FnTransport.send(transport.clj:34)
	at nrepl.middleware.print$send_streamed.invokeStatic(print.clj:136)
	at nrepl.middleware.print$send_streamed.invoke(print.clj:122)
	at nrepl.middleware.print$printing_transport$reify__1187.send(print.clj:173)
	at nrepl.middleware.caught$caught_transport$reify__1222.send(caught.clj:58)
	at cider.nrepl.middleware.debug$debugger_send.invokeStatic(debug.clj:202)
	at cider.nrepl.middleware.debug$debugger_send.doInvoke(debug.clj:195)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at cider.nrepl.middleware.debug$initialize.invokeStatic(debug.clj:642)
	at cider.nrepl.middleware.debug$initialize.invoke(debug.clj:638)
	at cider.nrepl.middleware.debug$handle_debug.invokeStatic(debug.clj:666)
	at cider.nrepl.middleware.debug$handle_debug.invoke(debug.clj:657)
	at clojure.lang.Var.invoke(Var.java:388)
	at cider.nrepl$wrap_debug$fn__3278.invoke(nrepl.clj:163)
	at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
	at nrepl.middleware.load_file$wrap_load_file$fn__1840.invoke(load_file.clj:81)
	at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
	at nrepl.middleware.session$add_stdin$fn__1416.invoke(session.clj:379)
	at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
	at cider.nrepl$wrap_content_type$fn__3236.invoke(nrepl.clj:107)
	at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
	at cider.nrepl$wrap_inspect$fn__3312.invoke(nrepl.clj:227)
	at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
	at cider.nrepl$wrap_out$fn__3336.invoke(nrepl.clj:334)
	at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
	at nrepl.middleware.caught$wrap_caught$fn__1231.invoke(caught.clj:97)
	at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
	at nrepl.middleware.print$wrap_print$fn__1198.invoke(print.clj:234)
	at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
	at cider.nrepl$wrap_tracker$fn__3400.invoke(nrepl.clj:520)
	at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
	at cider.nrepl$wrap_enlighten$fn__3286.invoke(nrepl.clj:190)
	at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
	at nrepl.middleware.sideloader$wrap_sideloader$fn__1921.invoke(sideloader.clj:108)
	at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
	at nrepl.middleware.session$session$fn__1401.invoke(session.clj:325)
	at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
	at refactor_nrepl.middleware$wrap_refactor$fn__3096.invoke(middleware.clj:244)
	at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
	at nrepl.server$default_handler$fn__1969.invoke(server.clj:141)
	at nrepl.
```

### Clojure version

```
Clojure CLI version 1.11.1.1347
```

### Java version

```
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)
OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)
```

### Operating system

```
$ uname -srvmpio
Linux 6.4.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Aug 2023 16:02:01 +0000 x86_64 unknown unknown GNU/Linux
```

**Comment by bbatsov** [comment]
@rlbdv Any idea what might be causing this?

**Comment by rlbdv** [comment]
Bozhidar Batsov ***@***.***> writes:

> @rlbdv Any idea what might be causing this? 

Not offhand.  (It'd be good to know the nrepl version.)  If the
stacktrace is compatible with main, it makes me wonder if something odd
is happening in the last catch clause in rethrow-on-disconnection.

i.e. could it be that type hint somehow?

**Comment by bbatsov** [comment]
Looking at the repro project the nREPL version is 1.0:

```
:paths   ["src"]
 :deps    {}
 :aliases {:socket-nrepl
           {:extra-deps {com.kohlschutter.junixsocket/junixsocket-common        {:mvn/version "2.7.0"}
                         com.kohlschutter.junixsocket/junixsocket-native-common {:mvn/version "2.7.0"}
                         nrepl/nrepl                                            {:mvn/version "1.0.0"}
                         cider/cider-nrepl                                      {:mvn/version "0.30.0"}
                         refactor-nrepl/refactor-nrepl                          {:mvn/version "3.9.0"}}
            :main-opts  ["-m" "nrepl.cmdline"
                         "--middleware" "[refactor-nrepl.middleware/wrap-refactor,cider.nrepl/cider-middleware]"
                         "--socket" "nrepl.sock"]}}}
```

**Comment by alexander-yakushev** [comment]
See #321.

**Comment by alexander-yakushev** [comment]
@rrudakov Could you please check if it is fixed for you?

**Comment by rrudakov** [comment]
Just have tested the fix on my work project. The issue is fixed, I tried to re-connect to the nrepl session multiple times without any errors. Thank you @alexander-yakushev !
