### ISSUE TITLE
Exception when using Ctrl-D in interactive mode

### ISSUE THREAD

**Issue by weavejester** [nrepl/nrepl#77]
## Expected behavior

Entering Ctrl-D in an interactive nREPL session makes it immediately exit.

## Actual behavior

Entering Ctrl-D throws an exception and hangs the process.

## Steps to reproduce the problem

```
$ clj -Sdeps '{:deps {nrepl {:mvn/version "0.4.5"}}}' -m nrepl.cmdline --interactive
nREPL server started on port 54732 on host 0:0:0:0:0:0:0:0 - nrepl://0:0:0:0:0:0:0:0:54732
nREPL 0.4.5
Clojure 1.9.0
Java HotSpot(TM) 64-Bit Server VM 10.0.2+13
user=> ^D
Exception in thread "main" clojure.lang.LispReader$ReaderException: java.lang.RuntimeException: EOF while reading
	at clojure.lang.LispReader.read(LispReader.java:304)
	at clojure.lang.LispReader.read(LispReader.java:206)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.core$read.invokeStatic(core.clj:3758)
	at clojure.core$read.invokeStatic(core.clj:3733)
	at clojure.core$read.invokeStatic(core.clj:3733)
	at clojure.core$read.invokeStatic(core.clj:3733)
	at clojure.core$read.invoke(core.clj:3733)
	at nrepl.cmdline$run_repl.invokeStatic(cmdline.clj:42)
	at nrepl.cmdline$run_repl.invoke(cmdline.clj:24)
	at nrepl.cmdline$_main.invokeStatic(cmdline.clj:179)
	at nrepl.cmdline$_main.doInvoke(cmdline.clj:138)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: EOF while reading
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.LispReader.read(LispReader.java:258)
	... 21 more
```

**Comment by bbatsov** [comment]
Yeah, we should fix this.

**Comment by mallt** [comment]
Changing the [cmdline message](https://github.com/nrepl/nrepl/blob/master/src/clojure/nrepl/cmdline.clj#L45) from
```clojure
{:op "eval" :code (pr-str (read))}
```

to 
```clojure
{:op "eval"
 :code (-> (read *in* false (read-string "(System/exit 0)"))
            pr-str)}
```

seems to do the trick by using the `eof-error?` and `eof-value` arguments of the read function.

Would this be an acceptable fix?
